sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"
  - "$HOME/.stack"
  - ".stack-work"

matrix:

  include:

  - ghc: 8.4.4
    env: STACK_YAML="$HOME/build/serokell/o-clock/stack-8.4.4.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.6.5
    env: STACK_YAML="$HOME/build/serokell/o-clock/stack.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.8.1
    env: STACK_YAML="$HOME/build/serokell/o-clock/stack-8.8.1.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.4.3
    env: GHCVER='8.4.3' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.3
        - cabal-install-head

  - ghc: 8.6.1
    env: GHCVER='8.6.1' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.1
        - cabal-install-head

  - ghc: 8.8.1
    env: GHCVER='8.8.1' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.8.1
        - cabal-install-head

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
      echo $PATH
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks -f aeson -f hashable -f serialise -f deepseq
    else
      mkdir -p ~/.local/bin
      export PATH="$HOME/.local/bin:$PATH"
      travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack --version
      stack setup --no-terminal --install-cabal 2.0.1.0
      stack ghc -- --version
      stack build --only-dependencies --no-terminal --flag o-clock:aeson --flag o-clock:hashable --flag o-clock:serialise --flag o-clock:deepseq
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test
    else
      stack build --test --no-terminal --flag o-clock:aeson --flag o-clock:hashable --flag o-clock:serialise --flag o-clock:deepseq
      # We use kinda dead packages (tiempo and time-units) in benchmarks, so we have to use `allow-newer` to build them.
      echo "allow-newer: true" >> $STACK_YAML
      stack build --bench --no-terminal --flag o-clock:aeson --flag o-clock:hashable --flag o-clock:serialise --flag o-clock:deepseq --flag o-clock:bench-buildable
    fi

notifications:
  email: false
  slack:
    rooms:
      - serokell:T7L0cju5Nrn6ZkqWJCwNuOh4
    on_success: change
    on_failure: always
